#!/usr/bin/env python3
"""
Does any of this actually reproduce?

Fifty-odd scripts written over weeks, nineteen reports, and a claim-verifier that
depends on a web of intermediate files. The README says the scripts are "numbered
in dependency order". This checks that claim instead of repeating it.

FOUR CHECKS
-----------
1. IMPORTS      every third-party module imported anywhere is in requirements.txt
2. PRODUCERS    every data/processed file a script READS is WRITTEN by some script
3. ORDER        no script reads a file produced by a HIGHER-numbered script
4. REFERENCES   every script named in a report or in the README exists

Static analysis, so it cannot prove the pipeline runs -- but a break in any of
these four is a break in the reproduction path, and nothing here needs the 9 GB
of raw data to check.

Usage: python3 scripts/55_reproducibility_audit.py
"""
from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPTS = REPO / "scripts"
REPORTS = REPO / "reports"

STDLIB = set(sys.stdlib_module_names) | {"__future__"}
# Import name -> distribution name, where they differ.
DIST = {"sklearn": "scikit-learn", "yaml": "PyYAML", "cv2": "opencv-python",
        "PIL": "Pillow", "mpl_toolkits": "matplotlib"}

FILE_RE = re.compile(r'([A-Za-z0-9_./*-]+\.(?:csv|json|npz|png|md|html))')

# Records committed by hand as part of a preregistration, deliberately not
# generated by any script -- that is the point of freezing them.
HAND_COMMITTED = {"FEATURE_STUDY_FROZEN.json", "COMBINATION_STUDY_FROZEN.json",
                  "FROZEN_DESIGN.json", "DETECTOR_V2_RECORD.json"}

# Files whose producer this audit cannot resolve, each verified by hand once.
# 18_reference_decoder.py reaches both through decoder_paths(), which RETURNS the
# path, so the string literal never appears near the np.savez / write_text that
# writes it. Following that needs interprocedural analysis, which is more machinery
# than a static audit should carry; naming them here keeps the check a clean gate
# instead of a permanently-failing one. Anything NOT on this list is a real finding.
RESOLVED_BY_HAND = {
    "reference_decoder.npz": "18_reference_decoder.py, via decoder_paths() -> np.savez",
    "reference_decoder.json": "18_reference_decoder.py, via decoder_paths() -> write_text",
}
SCRIPT_RE = re.compile(r'\b(\d{2}_[a-z0-9_]+\.py)\b')


def script_files() -> list[Path]:
    return sorted(p for p in SCRIPTS.glob("*.py") if re.match(r"\d{2}_", p.name))


def imports_of(path: Path) -> set[str]:
    try:
        tree = ast.parse(path.read_text())
    except SyntaxError:
        return set()
    out = set()
    for n in ast.walk(tree):
        if isinstance(n, ast.Import):
            out |= {a.name.split(".")[0] for a in n.names}
        elif isinstance(n, ast.ImportFrom) and n.level == 0 and n.module:
            out.add(n.module.split(".")[0])
    return {m for m in out if m not in STDLIB}


def _string_literals(tree) -> list[tuple[int, str]]:
    """(line, text) for every string in the file, f-strings flattened.

    An f-string is a JoinedStr whose literal parts are Constants; the earlier
    regex-only version captured only the tail after the last brace, which turned
    f"calibration_curve{sfx}.csv" into the filename "}.csv" and reported it as an
    orphan read by ten scripts. Flattening the AST node fixes that at the source.
    """
    out = []
    for n in ast.walk(tree):
        if isinstance(n, ast.Constant) and isinstance(n.value, str):
            out.append((getattr(n, "lineno", 0), n.value))
        elif isinstance(n, ast.JoinedStr):
            parts = []
            for v in n.values:
                if isinstance(v, ast.Constant) and isinstance(v.value, str):
                    parts.append(v.value)
                else:
                    parts.append("*")          # an interpolated segment
            out.append((getattr(n, "lineno", 0), "".join(parts)))
    return out


WRITE_CALL = re.compile(r"to_csv|write_text|savefig|np\.save|open\([^)]*['\"]w")
READ_CALL = re.compile(r"read_csv|read_text|np\.load|glob|exists|load\(")


def _assigned_paths(tree) -> dict[str, set[str]]:
    """Variable name -> filenames appearing in the expression assigned to it.

    Real code writes `ckpt = OUT / f"staleness{sfx}.csv"` and then
    `df.to_csv(ckpt)` many lines later, so a purely positional scan sees the
    filename with no write call near it and reports a producerless file. Two of
    the four remaining findings were exactly that. Following one level of
    assignment removes them without pretending to do full dataflow analysis.
    """
    out: dict[str, set[str]] = {}
    for n in ast.walk(tree):
        if not isinstance(n, ast.Assign):
            continue
        names = set()
        for sub in ast.walk(n.value):
            if isinstance(sub, ast.Constant) and isinstance(sub.value, str):
                names |= {m.group(1) for m in FILE_RE.finditer(sub.value)}
            elif isinstance(sub, ast.JoinedStr):
                txt = "".join(v.value if isinstance(v, ast.Constant)
                              and isinstance(v.value, str) else "*"
                              for v in sub.values)
                names |= {m.group(1) for m in FILE_RE.finditer(txt)}
        if not names:
            continue
        for t in n.targets:
            if isinstance(t, ast.Name):
                out.setdefault(t.id, set()).update(names)
    return out


def io_of(path: Path) -> tuple[set[str], set[str]]:
    """Filenames the script writes and reads.

    A name near a write call (to_csv, write_text, savefig, np.save, open(...w))
    counts as produced, near a read call as consumed. Interpolated segments
    become '*' so participant-suffixed variants unify with their base name.
    Filenames reached through a single assignment are resolved too.
    """
    src = path.read_text()
    lines = src.splitlines()
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return set(), set()
    writes, reads = set(), set()
    for lineno, text in _string_literals(tree):
        for m in FILE_RE.finditer(text):
            name = m.group(1)
            lo = max(0, lineno - 3)
            ctx = " ".join(lines[lo:lineno + 2])
            if WRITE_CALL.search(ctx):
                writes.add(name)
            elif READ_CALL.search(ctx):
                reads.add(name)

    # Second pass: filenames held in a variable, classified by how the VARIABLE
    # is used rather than by what sits near the string literal.
    assigned = _assigned_paths(tree)
    for var, names in assigned.items():
        for lineno, line in enumerate(lines, start=1):
            if not re.search(rf"\b{re.escape(var)}\b", line):
                continue
            if WRITE_CALL.search(line):
                writes |= names
            elif READ_CALL.search(line):
                reads |= names
    return writes, reads


def norm(n: str) -> str:
    """Collapse participant suffixes and interpolation marks to a base name."""
    n = n.rsplit("/", 1)[-1]
    n = re.sub(r"_T\d+", "", n)
    n = re.sub(r"\*", "", n)
    n = re.sub(r"_local|_contiguous", "", n)
    n = re.sub(r"__+", "_", n).replace("_.", ".")
    return n


def main() -> int:
    problems: list[str] = []
    scripts = script_files()
    print(f"auditing {len(scripts)} numbered scripts\n")

    # ---- 1. imports vs requirements -------------------------------------
    req_path = REPO / "requirements.txt"
    req = set()
    if req_path.exists():
        for line in req_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                req.add(re.split(r"[<>=!\[]", line)[0].strip().lower())
    used: dict[str, set[str]] = {}
    for p in scripts:
        for m in imports_of(p):
            used.setdefault(m, set()).add(p.name)
    missing = {m: v for m, v in used.items()
               if DIST.get(m, m).lower() not in req}
    print("1. IMPORTS")
    if missing:
        for m, v in sorted(missing.items()):
            problems.append(f"import '{m}' not in requirements.txt "
                            f"(used by {', '.join(sorted(v))})")
            print(f"   MISSING  {m:<16} used by {', '.join(sorted(v))}")
    else:
        print(f"   ok — all {len(used)} third-party imports are declared")

    # ---- 2 & 3. producers and ordering ----------------------------------
    produced: dict[str, str] = {}
    consumed: dict[str, set[str]] = {}
    for p in scripts:
        # This audit is a meta-tool, not a pipeline stage: it reads every script
        # and document in the repo, and its own tables name files it never
        # touches. Including it made it the recorded "producer" of the decoder
        # files, because the phrase "-> write_text" inside RESOLVED_BY_HAND
        # matched the write-call pattern. Excluding it is correct, not a dodge.
        if p.name == Path(__file__).name:
            continue
        w, r = io_of(p)
        # A file a script both writes and reads is produced by it; the read is
        # incidental (a checkpoint re-read, a re-load after saving).
        r -= w
        for f in w:
            produced.setdefault(norm(f), p.name)
        for f in r:
            consumed.setdefault(norm(f), set()).add(p.name)

    print("\n2. PRODUCERS")
    orphans = []
    for f, readers in sorted(consumed.items()):
        if f in produced:
            continue
        # Not expected to have a producer: raw inputs, hand-committed frozen
        # records, and documents the audit itself reads.
        if any(k in f for k in ("manifest", "raw/", "checksum")):
            continue
        if f in HAND_COMMITTED or f.endswith(".md"):
            continue
        if f in RESOLVED_BY_HAND:
            print(f"   (allowed)    {f:<38} produced by {RESOLVED_BY_HAND[f]}")
            continue
        orphans.append((f, readers))
    if orphans:
        for f, readers in orphans:
            problems.append(f"'{f}' is read by {', '.join(sorted(readers))} "
                            f"but no script writes it")
            print(f"   NO PRODUCER  {f:<38} read by {', '.join(sorted(readers))}")
    else:
        print(f"   ok — all {len(consumed)} consumed files have a producer")

    print("\n3. ORDER")
    # 31_verify_claims.py deliberately runs LAST -- it recomputes every headline
    # figure from whatever the pipeline produced, so it reads the output of most
    # other scripts. Its number reflects when it was written, not where it runs.
    # That is documented in the README rather than fixed by renumbering, which
    # would break the script names quoted throughout the reports.
    RUNS_LAST = {"31_verify_claims.py", "55_reproducibility_audit.py"}
    inversions = []
    for f, readers in sorted(consumed.items()):
        if f not in produced:
            continue
        pnum = int(produced[f][:2])
        for rd in readers:
            if rd in RUNS_LAST:
                continue
            if int(rd[:2]) < pnum:
                inversions.append((rd, f, produced[f]))
    if inversions:
        for rd, f, pr in inversions:
            problems.append(f"{rd} reads '{f}' produced by later script {pr}")
            print(f"   OUT OF ORDER  {rd} reads {f} written by {pr}")
    else:
        print("   ok — no script reads a file produced by a higher-numbered one")

    # ---- 4. references ---------------------------------------------------
    print("\n4. REFERENCES")
    have = {p.name for p in scripts}
    dangling = []
    docs = list(REPORTS.glob("*.md")) + [REPO / "README.md"] + \
        list((REPO / "research").glob("*.md"))
    for d in docs:
        if not d.exists():
            continue
        for m in SCRIPT_RE.finditer(d.read_text()):
            if m.group(1) not in have:
                dangling.append((d.name, m.group(1)))
    if dangling:
        for doc, s in sorted(set(dangling)):
            problems.append(f"{doc} names script '{s}' which does not exist")
            print(f"   DANGLING  {doc} -> {s}")
    else:
        print(f"   ok — every script named across {len(docs)} documents exists")

    out = {"n_scripts": len(scripts), "n_problems": len(problems),
           "problems": problems}
    (REPO / "data" / "processed" / "reproducibility_audit.json").write_text(
        json.dumps(out, indent=2))
    print(f"\n{'PASS — no problems found' if not problems else f'{len(problems)} problem(s)'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
