#!/usr/bin/env python3
"""
Is the headline detection number carried by one easy fault mode?

Preregistered in research/PER_MODE_DETECTION_NOTE.md, predictions included.

Claim C02 in the register -- session-level AUC 0.69 (T11) and 0.71 (T5) -- is
quoted throughout this project. GEOMETRY_ROTATION moves the `dispersion`
component by z = 16.5, nine times `profile` and far more than any other mode
produces, so the headline may be a mixture of one trivially detectable fault and
three that are not.

This decomposes the published number using EXACTLY the scores it was computed
from: same episodes, same early-warning windows, same shared healthy comparison
group. Nothing is recomputed, so a difference here is a property of the headline
rather than of a different analysis.

Usage: python3 scripts/59_per_mode_detection.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "processed"
REPORTS = REPO / "reports"


def auc(a, b):
    if len(a) < 5 or len(b) < 5:
        return float("nan")
    u, _ = stats.mannwhitneyu(a, b, alternative="two-sided")
    return float(u / (len(a) * len(b)))


def episode_scores(row) -> np.ndarray:
    return np.array([float(x) for x in str(row.scores).split(",") if x])


def main() -> int:
    results = {}
    md = ["# Is the detection headline carried by one fault mode?", "",
          "**Generated by `scripts/59_per_mode_detection.py` — do not edit by hand.**",
          "Preregistered in `research/PER_MODE_DETECTION_NOTE.md`.", "",
          "The headline (claim **C02**) decomposed by injected fault mode, using the",
          "same stored scores, the same early-warning windows and the same shared",
          "healthy comparison group. Nothing is recomputed.", ""]

    for P, f in [("T11", "episode_scores_local.csv"),
                 ("T5", "episode_scores_T5_local.csv")]:
        path = OUT / f
        if not path.exists():
            continue
        d = pd.read_csv(path)
        d = d[d.detector == "decoder_guard"]

        # TWO LEVELS, on purpose. The registered headline (claim C02) is a
        # WINDOW-level AUC: 31_verify_claims.py concatenates every window and
        # compares them individually. Every session-level analysis in this
        # project instead takes one median per episode -- and claim C04 says
        # windows within a session are not independent (lag-1 r = 0.995), so
        # the window-level number is a descriptive statistic, not an estimate
        # with a meaningful sample size. Both are computed here so the two are
        # visible side by side instead of being silently different.
        healthy, faulted = [], []
        healthy_w, faulted_w = [], []
        for _, r in d.iterrows():
            s = episode_scores(r)
            ow = int(r.onset_w)
            if len(s) <= ow:
                continue
            if not bool(r.crossed):
                healthy.append(float(np.median(s)))
                healthy_w.append(s)
                continue
            cw = int(r.crossing_w)
            if cw > ow and len(s) >= cw:
                faulted.append((r["mode"], float(np.median(s[ow:cw]))))
                faulted_w.append((r["mode"], s[ow:cw]))

        H = np.array(healthy)
        F = pd.DataFrame(faulted, columns=["mode", "score"])
        overall = auc(F.score.values, H)

        Hw = np.concatenate(healthy_w) if healthy_w else np.array([])
        by_mode_w = {}
        for m, arr in faulted_w:
            by_mode_w.setdefault(m, []).append(arr)
        Ew = np.concatenate([a for _, a in faulted_w]) if faulted_w else np.array([])
        overall_w = auc(Ew, Hw)

        rows = []
        for m, gg in F.groupby("mode"):
            wl = np.concatenate(by_mode_w[m]) if m in by_mode_w else np.array([])
            rows.append({"mode": m, "n": len(gg),
                         "auc": round(auc(gg.score.values, H), 4),
                         "auc_window_level": round(auc(wl, Hw), 4),
                         "n_windows": int(len(wl))})
        no_rot = F[F["mode"] != "GEOMETRY_ROTATION"]
        rot_only = F[F["mode"] == "GEOMETRY_ROTATION"]

        r = {"participant": P,
             "n_healthy": int(len(H)), "n_faulted": int(len(F)),
             "headline_auc_window_level_as_registered": round(overall_w, 4),
             "headline_auc": round(overall, 4),
             "auc_without_rotation": round(auc(no_rot.score.values, H), 4),
             "auc_rotation_only": round(auc(rot_only.score.values, H), 4)
             if len(rot_only) else None,
             "by_mode": rows}
        r["drop_from_removing_rotation"] = round(
            r["headline_auc"] - r["auc_without_rotation"], 4)
        best = max(rows, key=lambda x: x["auc"])
        r["highest_mode"] = best["mode"]
        r["prediction_1_rotation_highest_above_0.8"] = bool(
            best["mode"] == "GEOMETRY_ROTATION" and best["auc"] > 0.8)
        results[P] = r

        print(f"=== {P} ===")
        print(f"  window-level AUC (as registered) "
              f"{r['headline_auc_window_level_as_registered']:.3f}")
        print(f"  episode-level AUC                {r['headline_auc']:.3f}   "
              f"({len(F)} faulted vs {len(H)} healthy episodes)")
        for row in sorted(rows, key=lambda x: -x["auc"]):
            print(f"    {row['mode']:<20} n={row['n']:>4}   "
                  f"episode {row['auc']:.3f}   window {row['auc_window_level']:.3f}")
        print(f"  rotation only      {r['auc_rotation_only']}")
        print(f"  WITHOUT rotation   {r['auc_without_rotation']:.3f}   "
              f"(drop {r['drop_from_removing_rotation']:+.3f})\n")

        md += [f"## {P}", "",
               f"Window-level (as registered in claim C02): "
               f"**{r['headline_auc_window_level_as_registered']:.3f}**. "
               f"Episode-level: **{r['headline_auc']:.3f}**, over {len(F)} faulted "
               f"and {len(H)} healthy episodes.", "",
               "| injected fault | n episodes | AUC (episode) | AUC (window) |",
               "|---|---|---|---|"]
        for row in sorted(rows, key=lambda x: -x["auc"]):
            bold = "**" if row["mode"] == "GEOMETRY_ROTATION" else ""
            md.append(f"| `{row['mode']}` | {row['n']} | {bold}{row['auc']:.3f}{bold} "
                      f"| {row['auc_window_level']:.3f} |")
        md += ["",
               f"| | AUC |", "|---|---|",
               f"| headline, all modes | **{r['headline_auc']:.3f}** |",
               f"| rotation alone | {r['auc_rotation_only']:.3f} |",
               f"| **all modes except rotation** | **{r['auc_without_rotation']:.3f}** |",
               "",
               f"Removing rotation moves the headline by "
               f"**{r['drop_from_removing_rotation']:+.3f}**.", ""]

    t11 = results.get("T11", {})
    t5 = results.get("T5", {})
    md += ["## The prediction was wrong, on both counts", "",
           "`research/PER_MODE_DETECTION_NOTE.md` predicted (1) that "
           "`GEOMETRY_ROTATION` would have the highest per-mode AUC, above 0.8, and "
           "(2) that removing it would drop the headline to 0.60–0.65.", "",
           "| | predicted | T11 | T5 |", "|---|---|---|---|",
           f"| rotation is the highest mode | yes | highest, but at "
           f"{t11.get('auc_rotation_only', float('nan')):.3f} — **below 0.8**, and tied "
           f"with GAIN_DRIFT (0.787) | **third**, at "
           f"{t5.get('auc_rotation_only', float('nan')):.3f} |",
           f"| headline without rotation | 0.60–0.65 | "
           f"{t11.get('auc_without_rotation', float('nan')):.3f} "
           f"(drop {t11.get('drop_from_removing_rotation', 0):+.3f}) | "
           f"{t5.get('auc_without_rotation', float('nan')):.3f} "
           f"(drop {t5.get('drop_from_removing_rotation', 0):+.3f}) |", "",
           "**The headline is not carried by one easy fault mode.** Claim C02 stands "
           "as registered. On T5 removing rotation changes it by 0.002.", "",
           "### Why a 16σ signal does not give easy detection", "",
           "`GEOMETRY_ROTATION` moves the `dispersion` component by **z = 16.5** "
           "during the early-warning window, yet detects at only 0.75–0.79. That is "
           "not a contradiction — it is the project's central finding in another "
           "form. The risk score is the largest of four calibrated components, and "
           "**healthy episodes produce large component values too**: that is exactly "
           "why no configuration passes the silence gate. A fault signal sixteen "
           "deviations from the healthy median still overlaps a healthy distribution "
           "that is itself wide and heavy-tailed.", "",
           "Separability and detectability are different questions. Rotation is the "
           "most *separable* mode (`MODE_SEPARABILITY.md`, AUC 0.86–1.00 against the "
           "other modes) and only a middling *detectable* one, because separating two "
           "faults from each other is easier than separating a fault from healthy "
           "recording.", "",
           "### The modes disagree between participants, again", "",
           "`CHANNEL_DROPOUT` is the **worst** mode on T11 (0.560) and the **best** on "
           "T5 (0.798). This is the same disagreement `ATTRIBUTION_ACCURACY.md` found, "
           "and it is why no per-mode claim in this project is stated as general.", "",
           "### A sanity check that passes", "",
           "The `NONE` control episodes — no fault injected, but they crossed the "
           "threshold by noise — score **below** the healthy group (0.163 on T11, "
           "0.387 on T5). If the pipeline were mislabelling episodes, these would sit "
           "with the faults. They do not.", "",
           "### A discrepancy this exposed, and it is real", "",
           "The registered headline is a **window-level** AUC: `31_verify_claims.py` "
           "concatenates every window and compares them individually. Every "
           "session-level analysis in this project instead takes one median per "
           "episode. Both are reported above and they differ: "
           f"{t11.get('headline_auc_window_level_as_registered', 0):.3f} vs "
           f"{t11.get('headline_auc', 0):.3f} on T11, and "
           f"{t5.get('headline_auc_window_level_as_registered', 0):.3f} vs "
           f"{t5.get('headline_auc', 0):.3f} on T5 — in opposite directions.", "",
           "Claim **C04** says windows within a session are not independent "
           "(lag-1 r = 0.995), so the window-level figure is a descriptive statistic "
           "and not an estimate with a meaningful sample size. Its point value is "
           "sound; a confidence interval or p-value built on it would not be. The "
           "register now records that C02's number is window-level.", ""]

    (OUT / "per_mode_detection.json").write_text(json.dumps(results, indent=2))
    (REPORTS / "PER_MODE_DETECTION.md").write_text("\n".join(md) + "\n")
    print(f"wrote {REPORTS / 'PER_MODE_DETECTION.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
