#!/usr/bin/env python3
"""
Is the headline detection number carried by one easy fault mode?

Preregistered in research/PER_MODE_DETECTION_NOTE.md, predictions included.

Claim C02 in the register -- session-level AUC 0.69 (T11) and 0.71 (T5) -- is
quoted throughout this project. GEOMETRY_ROTATION moves the `dispersion`
component by z = 16.5, nine times `profile` and far more than any other mode
produces, so the headline may be a mixture of one trivially detectable fault and
three that are not.

This decomposes the published number using EXACTLY the scores it was computed
from: same episodes, same early-warning windows, same shared healthy comparison
group. Nothing is recomputed, so a difference here is a property of the headline
rather than of a different analysis.

Usage: python3 scripts/59_per_mode_detection.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "processed"
REPORTS = REPO / "reports"


def auc(a, b):
    if len(a) < 5 or len(b) < 5:
        return float("nan")
    u, _ = stats.mannwhitneyu(a, b, alternative="two-sided")
    return float(u / (len(a) * len(b)))


def episode_scores(row) -> np.ndarray:
    return np.array([float(x) for x in str(row.scores).split(",") if x])


def main() -> int:
    results = {}
    md = ["# Is the detection headline carried by one fault mode?", "",
          "**Generated by `scripts/59_per_mode_detection.py` — do not edit by hand.**",
          "Preregistered in `research/PER_MODE_DETECTION_NOTE.md`.", "",
          "The headline (claim **C02**) decomposed by injected fault mode, using the",
          "same stored scores, the same early-warning windows and the same shared",
          "healthy comparison group. Nothing is recomputed.", ""]

    for P, f in [("T11", "episode_scores_local.csv"),
                 ("T5", "episode_scores_T5_local.csv")]:
        path = OUT / f
        if not path.exists():
            continue
        d = pd.read_csv(path)
        d = d[d.detector == "decoder_guard"]

        healthy, faulted = [], []
        for _, r in d.iterrows():
            s = episode_scores(r)
            ow = int(r.onset_w)
            if len(s) <= ow:
                continue
            if not bool(r.crossed):
                healthy.append(float(np.median(s)))
                continue
            cw = int(r.crossing_w)
            if cw > ow and len(s) >= cw:
                faulted.append((r["mode"], float(np.median(s[ow:cw]))))

        H = np.array(healthy)
        F = pd.DataFrame(faulted, columns=["mode", "score"])
        overall = auc(F.score.values, H)

        rows = []
        for m, gg in F.groupby("mode"):
            rows.append({"mode": m, "n": len(gg),
                         "auc": round(auc(gg.score.values, H), 4)})
        no_rot = F[F["mode"] != "GEOMETRY_ROTATION"]
        rot_only = F[F["mode"] == "GEOMETRY_ROTATION"]

        r = {"participant": P,
             "n_healthy": int(len(H)), "n_faulted": int(len(F)),
             "headline_auc": round(overall, 4),
             "auc_without_rotation": round(auc(no_rot.score.values, H), 4),
             "auc_rotation_only": round(auc(rot_only.score.values, H), 4)
             if len(rot_only) else None,
             "by_mode": rows}
        r["drop_from_removing_rotation"] = round(
            r["headline_auc"] - r["auc_without_rotation"], 4)
        best = max(rows, key=lambda x: x["auc"])
        r["highest_mode"] = best["mode"]
        r["prediction_1_rotation_highest_above_0.8"] = bool(
            best["mode"] == "GEOMETRY_ROTATION" and best["auc"] > 0.8)
        results[P] = r

        print(f"=== {P} ===")
        print(f"  headline AUC {r['headline_auc']:.3f}   "
              f"({len(F)} faulted vs {len(H)} healthy episodes)")
        for row in sorted(rows, key=lambda x: -x["auc"]):
            print(f"    {row['mode']:<20} n={row['n']:>4}   AUC {row['auc']:.3f}")
        print(f"  rotation only      {r['auc_rotation_only']}")
        print(f"  WITHOUT rotation   {r['auc_without_rotation']:.3f}   "
              f"(drop {r['drop_from_removing_rotation']:+.3f})\n")

        md += [f"## {P}", "",
               f"Headline **{r['headline_auc']:.3f}** over {len(F)} faulted and "
               f"{len(H)} healthy episodes.", "",
               "| injected fault | n | AUC |", "|---|---|---|"]
        for row in sorted(rows, key=lambda x: -x["auc"]):
            bold = "**" if row["mode"] == "GEOMETRY_ROTATION" else ""
            md.append(f"| `{row['mode']}` | {row['n']} | {bold}{row['auc']:.3f}{bold} |")
        md += ["",
               f"| | AUC |", "|---|---|",
               f"| headline, all modes | **{r['headline_auc']:.3f}** |",
               f"| rotation alone | {r['auc_rotation_only']:.3f} |",
               f"| **all modes except rotation** | **{r['auc_without_rotation']:.3f}** |",
               "",
               f"Removing rotation moves the headline by "
               f"**{r['drop_from_removing_rotation']:+.3f}**.", ""]

    (OUT / "per_mode_detection.json").write_text(json.dumps(results, indent=2))
    (REPORTS / "PER_MODE_DETECTION.md").write_text("\n".join(md) + "\n")
    print(f"wrote {REPORTS / 'PER_MODE_DETECTION.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
