#!/usr/bin/env python3
"""
66_window_spacing.py
====================
Is lag-1 r = 0.995 a fact about the signal, or about the windowing?

THE OBJECTION THIS ANSWERS
--------------------------
Claim C04 -- "a session contains roughly one independent measurement, lag-1
autocorrelation 0.995" -- is the single number that explains most of this
project's negative results. It is computed on a series of 30-second windows
that step every 5 seconds.

Adjacent windows therefore share 25 of their 30 seconds: 1250 of 1500 bins,
or 83.3% of their data. SOME autocorrelation is forced by that geometry alone,
regardless of what the underlying signal does. A reader is entitled to ask how
much of 0.995 is the brain and how much is the window.

Nobody asked until now. This measures it.

THE METHOD
----------
Take the same healthy episodes scripts/29 uses, and recompute lag-1
autocorrelation on decimated versions of each risk series:

    every window   -> adjacent windows share 1250/1500 bins = 83.3%
    every 3rd      -> share  750/1500 = 50.0%
    every 6th      -> share    0/1500 =  0.0%    <-- no shared data at all
    every 9th      -> share    0/1500 =  0.0%    (and 30 s further apart)

If the published 0.995 were mostly geometry, r would collapse toward zero at
the no-overlap spacing. Whatever survives there is a property of the signal.

WHY IT MATTERS BEYOND TIDINESS
------------------------------
The rig study (research/RIG_PROCEDURE.md) compares the physical array's
autocorrelation against this project's. It must compare against the
NO-OVERLAP number, because the rig will use its own window geometry and an
overlap-inflated figure is not a property of the system being compared.
Prediction P-R1 in the rig preregistration quotes the numbers this script
produces, so they have to come from committed code rather than from an
analysis run once by hand. That mistake has been made in this project before
(reports/REPRODUCIBILITY_AUDIT.md, finding 1).

Usage: python3 scripts/66_window_spacing.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "processed"
REPORTS = REPO / "reports"

SOURCES = [("episode_scores_local.csv", "T11"), ("episode_scores_T5_local.csv", "T5")]

WINDOW_BINS = 1500          # must match scripts/20_evaluation_harness.py
STEP_BINS = 250             # must match scripts/20_evaluation_harness.py

# Decimation factors. A factor k means "keep every k-th window", so adjacent
# kept windows are k * STEP_BINS bins apart.
SPACINGS = [1, 3, 6, 9]

MIN_WINDOWS = 12            # below this, a lag-1 estimate is not worth having


def overlap_fraction(k: int) -> float:
    """Fraction of bins two adjacent kept windows share, at decimation k."""
    shared = max(0, WINDOW_BINS - k * STEP_BINS)
    return shared / WINDOW_BINS


def lag1(y: np.ndarray) -> float:
    if len(y) < 6:
        return np.nan
    a, b = y[:-1], y[1:]
    if a.std() < 1e-12 or b.std() < 1e-12:
        return np.nan
    return float(np.corrcoef(a, b)[0, 1])


def n_eff(n: float, r: float) -> float:
    """Effective independent samples, the standard first-order correction.

    Identical to the formula scripts/29_aggregation_limit.py uses, so the two
    numbers are comparable by construction.
    """
    return n * (1 - r) / (1 + r)


def main() -> int:
    result: dict = {"window_bins": WINDOW_BINS, "step_bins": STEP_BINS}

    L = ["# How much of lag-1 r = 0.995 is the signal, and how much is the window?\n",
         "**Generated by `scripts/66_window_spacing.py` — do not edit by hand.**\n",
         "Claim **C04** is computed on 30-second windows stepping 5 seconds, so "
         "adjacent windows share **83.3%** of their data. Some autocorrelation is "
         "forced by that geometry whatever the signal does. This decimates the "
         "series until adjacent windows share nothing, and reports what survives.\n"]
    A = L.append

    A("## Lag-1 autocorrelation against window spacing\n")
    A("| Participant | Spacing | Bins apart | Data shared | Windows | Lag-1 r | "
      "Effective independent samples |")
    A("|---|---|---|---|---|---|---|")

    for fname, pname in SOURCES:
        path = OUT / fname
        if not path.exists():
            continue
        df = pd.read_csv(path)
        sub = df[df.detector == "decoder_guard"]
        # "Healthy" here is exactly scripts/29's definition: episodes whose
        # injected fault never pushed the decoder past its threshold.
        ys = [np.fromstring(r.scores, sep=",")
              for _, r in sub.iterrows() if not r.crossed]
        ys = [y for y in ys if len(y) >= MIN_WINDOWS]

        result[pname] = {"n_episodes": len(ys), "spacings": {}, "skipped": {}}
        for k in SPACINGS:
            rs = [lag1(y[::k]) for y in ys]
            rs = [v for v in rs if np.isfinite(v)]
            ns = [len(y[::k]) for y in ys]
            if not rs:
                # Report the gap rather than leaving a row silently missing.
                kept = float(np.median(ns)) if ns else 0.0
                result[pname]["skipped"][str(k)] = {
                    "reason": "fewer than 6 windows survive decimation",
                    "median_windows_after_decimation": kept,
                }
                A(f"| {pname} | every {k} | {k * STEP_BINS} | "
                  f"{overlap_fraction(k) * 100:.1f}% | {kept:.0f} | "
                  f"*not estimable* | — |")
                continue
            r_med, n_med = float(np.median(rs)), float(np.median(ns))
            e = n_eff(n_med, r_med)
            ov = overlap_fraction(k)
            flag = " **" if ov == 0.0 and k == 6 else ""
            A(f"| {pname} | every {k} | {k * STEP_BINS} | {ov * 100:.1f}% | "
              f"{n_med:.0f} | {flag}{r_med:.3f}{flag} | {e:.2f} |")
            result[pname]["spacings"][str(k)] = {
                "overlap_fraction": ov, "n_windows_median": n_med,
                "lag1_r_median": r_med, "n_eff": e, "n_episodes": len(rs),
            }

    A("")
    A("*not estimable* = after decimation fewer than 6 windows remain per "
      "episode, which is too short for a lag-1 estimate. The row is shown "
      "rather than omitted, so the table cannot be misread as a result that "
      "stops where the trend stops being convenient.\n")
    A("## What this shows\n")

    t11 = result.get("T11", {}).get("spacings", {})
    t5 = result.get("T5", {}).get("spacings", {})
    if "1" in t11 and "6" in t11:
        A(f"- **The correlation is real, not geometry.** At zero overlap the "
          f"lag-1 autocorrelation is still **{t11['6']['lag1_r_median']:.3f}** on "
          f"T11 and **{t5['6']['lag1_r_median']:.3f}** on T5. Had the published "
          f"{t11['1']['lag1_r_median']:.3f} been mostly forced by the 83.3% "
          f"overlap, it would have collapsed toward zero here. It does not.")
        worst = max(v["n_eff"] for v in list(t11.values()) + list(t5.values()))
        A(f"- **The conclusion is unchanged at every spacing.** Effective "
          f"independent samples per session never exceeds **{worst:.2f}**. There "
          f"is no windowing choice available here that buys a second independent "
          f"measurement, which is what claim C04 asserts.")
        A(f"- **But the published figure is partly geometric, and should not be "
          f"quoted against a system with different windowing.** Comparisons to "
          f"any other array — including the rig in `research/RIG_PROCEDURE.md` — "
          f"must use the no-overlap row "
          f"(**{t11['6']['lag1_r_median']:.3f}** / "
          f"**{t5['6']['lag1_r_median']:.3f}**), not "
          f"{t11['1']['lag1_r_median']:.3f} / {t5['1']['lag1_r_median']:.3f}.")

    A("")
    A("## Limits of this check\n")
    A("- Decimation shortens the series: T11 drops from ~55 windows to ~10 at "
      "the no-overlap spacing, so each per-episode estimate is noisier. The "
      "median across hundreds of episodes is what is reported, not any one "
      "episode.")
    A("- Zero *shared bins* is not the same as zero *shared cause*. Two windows "
      "30 seconds apart still sit inside the same block, under the same "
      "electrode state. That is the point — it is what genuine slow structure "
      "means — but it is worth saying rather than implying independence.")
    A("- This measures `decoder_guard` only. A different detector could carry a "
      "different amount of geometric inflation.")

    (OUT / "window_spacing.json").write_text(json.dumps(result, indent=2))
    (REPORTS / "WINDOW_SPACING.md").write_text("\n".join(L))
    print("\n".join(L[3:]).replace("**", ""))
    print(f"\nwrote {REPORTS / 'WINDOW_SPACING.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
