#!/usr/bin/env python3
"""
74_session_level_monitor.py
===========================
The monitor failed within a session. Does it work BETWEEN sessions?

THE ARGUMENT
------------
Everything in this project so far monitored inside a recording session: 30-second
windows stepping 5 seconds, 720 decisions an hour. That failed, and
reports/OPERATING_POINT_BOUND.md says why in one line -- a false-alarm budget of
2.4 alarms a day, spread across 720 decisions an hour, demands a per-decision
false-positive rate of 1.4e-4, which needs an AUC of 0.9992. The observed AUC is
0.693. The information is there; the decision rate destroys it.

Put that beside the other headline finding: a session contains roughly ONE
independent measurement (claim C04). The monitor was making 720 decisions an
hour out of one measurement's worth of evidence. That is not a detector problem.
It is a sampling-rate problem, and it is entirely self-inflicted.

So this asks the obvious next question, which nothing in this project had asked:
what happens if the monitor makes ONE decision per session instead?

At that rate the arithmetic inverts. T11 has 15 sessions across 142 days and T5
has 6 across 28 days, and -- unlike windows five seconds apart -- sessions days
apart really are close to independent.

WHAT THE DRIFT MEASURE ACTUALLY IS
----------------------------------
`cosine_to_first_session` comes from scripts/05_check_decoder_stability.py. In
every block it fits a linear map from the recorded neural features (`nctx`, plus
`spikePower`) to `cursorVel`, then reports the cosine similarity between that
session's fitted weights and the first session's.

Two corrections to how this was first described here, both of which matter:

  * It is **not** "neural covariance geometry". It is a comparison of fitted
    decoder weights. Those are different objects and the first description was
    simply wrong.
  * It is **not** neural-only. It uses `cursorVel`, the decoder's own output.

It IS free of task labels and of performance measures -- it never touches
`angleError`, `trialSuccess` or the intended target -- and both of its inputs are
logged automatically during ordinary use. So it could run without asking the
user to do anything, which is the property that matters for deployment. But
"neural-only" was the wrong word and it was load-bearing, so it is corrected
here rather than quietly dropped.

WHAT THIS IS AND IS NOT
-----------------------
**This is exploratory and was not preregistered.** Everything else in this
project fixed its predictions before looking; this looked first. It is reported
as a hypothesis generated by the data, which is what it is, and the honest next
step is to preregister it and test it on the rig rather than to present it as a
confirmed result. Saying so is the difference between a new direction and the
same mistake this project was built to avoid.

It is also observational. Nobody wrote down when T11's array began to fail, so
the lead time below depends on where the failure is defined -- exactly the
problem that motivated building fault injection in the first place. The
difference is that at this scale the degradation is not subtle: median angular
error goes from 22 degrees to 121.

Usage: python3 scripts/74_session_level_monitor.py
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "data" / "processed"
REPORTS = REPO / "reports"

# A session counts as failed once its median angular error exceeds this multiple
# of the participant's own first-session error. Relative, because T11 and T5
# start at different places; 2.0 because a doubling is not a subtle change and
# does not depend on a fine judgement call.
FAIL_MULTIPLE = 2.0

# Three ways to say when the array "failed", because there is no recorded onset
# and the answer changes with the definition. That sensitivity is the whole
# reason this project built fault injection, so it is measured here rather than
# hidden behind whichever definition flatters the result.
#
#   first     the first session over threshold
#   sustained the first session over threshold that STAYS over it
#   recovery  noted separately -- T11 crosses at day 727, recovers to 21.8 deg at
#             751, then collapses at 758. A single crossing is not a failure if
#             the array comes back.
FAILURE_DEFS = ["first", "sustained"]

# The monitor warns when the neural drift measure falls below this fraction of
# its own starting value. One free parameter, swept below rather than chosen.
WARN_FRACTIONS = [0.85, 0.80, 0.75, 0.70, 0.65, 0.60, 0.55, 0.50]


def load() -> pd.DataFrame:
    stab = pd.read_csv(OUT / "decoder_stability.csv")
    trials = pd.read_csv(OUT / "trials.csv")
    perf = (trials.groupby(["participant", "trial_day"])
            .angle_error_deg.median().reset_index(name="median_error_deg"))
    return stab.merge(perf, on=["participant", "trial_day"]).sort_values(
        ["participant", "trial_day"]).reset_index(drop=True)


def failure_index(failed: pd.Series, how: str) -> int | None:
    """Which session counts as the failure, under one definition."""
    if not failed.any():
        return None
    if how == "first":
        return int(failed.idxmax())
    # sustained: the first crossing after which it never recovers
    arr = failed.to_numpy()
    for i in range(len(arr)):
        if arr[i] and arr[i:].all():
            return int(i)
    return None


def analyse(s: pd.DataFrame) -> dict:
    """One participant's session series."""
    s = s.reset_index(drop=True)
    base_err = s.median_error_deg.iloc[0]
    fail_thresh = base_err * FAIL_MULTIPLE
    failed = s.median_error_deg > fail_thresh

    c = s.cosine_to_first_session.to_numpy()
    e = s.median_error_deg.to_numpy()
    day = s.trial_day.to_numpy(dtype=float)
    rho, pval = stats.spearmanr(c, e)

    # Both series move with time, and two series that both trend will correlate
    # whether or not one tells you anything about the other. So the raw number
    # above is not evidence on its own. Two standard checks:
    #
    #   partial      rank correlation with the day trend regressed out of both
    #   differences  does a CHANGE in drift go with a CHANGE in error?
    #
    # Neither is decisive at n = 15, and they do not have to agree. Reporting
    # both, including when they disagree, is the point.
    def _rank(x):
        return stats.rankdata(x)

    def _resid(x, ctrl):
        return x - np.polyval(np.polyfit(ctrl, x, 1), ctrl)

    rc = _rank(day)
    pr, pp = stats.pearsonr(_resid(_rank(c), rc), _resid(_rank(e), rc))
    dr, dp = stats.spearmanr(np.diff(c), np.diff(e))
    trend_c = stats.spearmanr(day, c)
    trend_e = stats.spearmanr(day, e)

    robustness = {
        "raw_rho": float(rho), "raw_p": float(pval),
        "day_vs_drift_rho": float(trend_c.statistic),
        "day_vs_drift_p": float(trend_c.pvalue),
        "day_vs_error_rho": float(trend_e.statistic),
        "day_vs_error_p": float(trend_e.pvalue),
        "partial_rho": float(pr), "partial_p": float(pp),
        "diff_rho": float(dr), "diff_p": float(dp),
        "survives_partial": bool(pp < 0.05),
        "survives_differences": bool(dp < 0.05 and dr < 0),
    }

    defs = {}
    for how in FAILURE_DEFS:
        fi = failure_index(failed, how)
        rows = []
        for f in WARN_FRACTIONS:
            warned = s.cosine_to_first_session < f
            fw = int(warned.idxmax()) if warned.any() else None
            if fi is None or fw is None or fw > fi:
                lead, early = None, None
            else:
                lead = int(s.trial_day.iloc[fi] - s.trial_day.iloc[fw])
                # Sessions that warned while performance was still fine. This is
                # the cost of the warning: each is a recalibration nobody needed.
                early = int((warned[:fi] & ~failed[:fi]).sum())
            rows.append({
                "warn_fraction": f,
                "first_warn_day": None if fw is None else int(s.trial_day.iloc[fw]),
                "lead_days": lead,
                "warned_before_failure": bool(lead is not None),
                "healthy_sessions_warned": early,
            })
        defs[how] = {
            "failure_session_index": fi,
            "failure_day": None if fi is None else int(s.trial_day.iloc[fi]),
            "operating_points": rows,
        }

    # Does it ever recover after crossing? If so, "first crossing" is not a
    # failure and the lead times computed from it are optimistic.
    fi_first = failure_index(failed, "first")
    recovers = bool(fi_first is not None and (~failed[fi_first:]).any())

    return {
        "n_sessions": int(len(s)),
        "day_span": int(s.trial_day.iloc[-1] - s.trial_day.iloc[0]),
        "baseline_error_deg": float(base_err),
        "failure_threshold_deg": float(fail_thresh),
        "recovers_after_first_crossing": recovers,
        "final_error_deg": float(s.median_error_deg.iloc[-1]),
        "spearman_rho": float(rho), "spearman_p": float(pval),
        "robustness": robustness,
        "by_failure_definition": defs,
        "series": s[["trial_day", "cosine_to_first_session",
                     "median_error_deg"]].to_dict("records"),
    }


def main() -> int:
    df = load()
    result = {
        "what_this_is": "EXPLORATORY, NOT PREREGISTERED. A hypothesis generated "
                        "by the data, to be preregistered and tested on the rig.",
        "failure_definition": f"median angular error above {FAIL_MULTIPLE}x the "
                              f"participant's own first session",
        "participants": {},
    }
    for p in sorted(df.participant.unique()):
        result["participants"][p] = analyse(df[df.participant == p])
    (OUT / "session_level_monitor.json").write_text(json.dumps(result, indent=2))

    L = ["# The monitor failed within a session. Does it work between sessions?\n",
         "**Generated by `scripts/74_session_level_monitor.py` — do not edit by hand.**\n",
         "> **Exploratory. Not preregistered.** Every other result in this project "
         "fixed its prediction before looking. This looked first, so it is a "
         "hypothesis generated by the data rather than a confirmed finding. The "
         "honest next step is to preregister it and test it on the rig. Saying so "
         "is the difference between a new direction and the mistake this project "
         "was built to avoid.\n"]
    A = L.append

    A("## Why ask this at all\n")
    A("`reports/OPERATING_POINT_BOUND.md` explains the within-session failure in "
      "one line: a budget of 2.4 alarms a day spread across **720 decisions an "
      "hour** demands a per-decision false-positive rate of 1.4e-4, which needs "
      "an **AUC of 0.9992**. The observed AUC is **0.693**. The information is "
      "present; the decision rate destroys it.\n")
    A("Put that beside claim **C04** — a session holds roughly **one independent "
      "measurement**. The monitor was making 720 decisions an hour from one "
      "measurement's worth of evidence. That is a sampling-rate problem, not a "
      "detector problem, and it was self-inflicted.\n")
    A("So: one decision per session instead.\n")

    for p, r in result["participants"].items():
        A(f"## {p}\n")
        A(f"{r['n_sessions']} sessions across {r['day_span']} days. Failure is "
          f"median angular error above **{r['failure_threshold_deg']:.1f}°**, "
          f"which is {FAIL_MULTIPLE:.0f}× this participant's own first session "
          f"({r['baseline_error_deg']:.1f}°).\n")
        A("| Day | Neural drift measure | Median error | Over threshold |")
        A("|---|---|---|---|")
        for row in r["series"]:
            over = row["median_error_deg"] > r["failure_threshold_deg"]
            A(f"| {row['trial_day']} | {row['cosine_to_first_session']:.3f} | "
              f"{row['median_error_deg']:.1f}° | {'**yes**' if over else 'no'} |")
        A("")
        rb = r["robustness"]
        A(f"Raw correlation between the drift measure and performance: "
          f"**rho = {r['spearman_rho']:+.3f}, p = {r['spearman_p']:.4f}**.\n")
        A("**That figure is inflated and must not be quoted alone.** Both series "
          "move with time, and any two series that trend together correlate "
          "whether or not one says anything about the other:\n")
        A("| Check | Result | Verdict |")
        A("|---|---|---|")
        A(f"| Day vs drift measure | rho = {rb['day_vs_drift_rho']:+.3f}, "
          f"p = {rb['day_vs_drift_p']:.4f} | both trend strongly |")
        A(f"| Day vs performance error | rho = {rb['day_vs_error_rho']:+.3f}, "
          f"p = {rb['day_vs_error_p']:.4f} | |")
        A(f"| **Partial**, day regressed out of both | "
          f"rho = {rb['partial_rho']:+.3f}, p = {rb['partial_p']:.4f} | "
          f"{'survives' if rb['survives_partial'] else '**does not survive**'} |")
        A(f"| **First differences** — does a change in drift accompany a change "
          f"in error? | rho = {rb['diff_rho']:+.3f}, p = {rb['diff_p']:.4f} | "
          f"{'survives' if rb['survives_differences'] else '**does not survive**'} |")
        A("")

        if r["recovers_after_first_crossing"]:
            d = r["by_failure_definition"]
            A(f"> **The array recovers after its first crossing, so the lead time "
              f"depends on what counts as failure.** {p} crosses at day "
              f"{d['first']['failure_day']}, comes back inside threshold, then "
              f"collapses at day {d['sustained']['failure_day']}. **This is the "
              f"exact problem that motivated building fault injection in the "
              f"first place** — in observational data nobody recorded the onset, "
              f"so the analyst picks it afterwards and the lead time moves with "
              f"the choice. Both are reported below. Neither is the right answer; "
              f"having to choose is the finding.\n")

        for how, d in r["by_failure_definition"].items():
            if d["failure_day"] is None:
                A(f"**{how} failure:** never reached.\n")
                continue
            label = ("first crossing" if how == "first"
                     else "first crossing it never recovers from")
            A(f"**Failure defined as the {label} — day {d['failure_day']}:**\n")
            A("| Warn when drift falls below | First warning | Lead time | "
              "Healthy sessions warned |")
            A("|---|---|---|---|")
            for op in d["operating_points"]:
                A(f"| {op['warn_fraction']:.2f} | "
                  f"{'day ' + str(op['first_warn_day']) if op['first_warn_day'] else 'never'} | "
                  f"{str(op['lead_days']) + ' days' if op['lead_days'] is not None else '— (too late)'} | "
                  f"{op['healthy_sessions_warned']} |")
            A("")

    t11 = result["participants"].get("T11", {})
    best = None
    for how in ("sustained", "first"):
        ops = t11.get("by_failure_definition", {}).get(how, {}).get("operating_points", [])
        clean = [o for o in ops if o["lead_days"] is not None
                 and o["healthy_sessions_warned"] == 0]
        if clean:
            best = (how, max(clean, key=lambda o: o["lead_days"]))
            break

    A("## Next to the within-session result\n")
    A("| | Within session | Between sessions |")
    A("|---|---|---|")
    A("| Decisions per hour | 720 | about 0.2 |")
    A("| Independent measurements | ~1 per session | 1 per session × 15 sessions |")
    A("| Healthy records showing a spurious trend | **98.1%** | see tables above |")
    A(f"| Median lead time (T11) | **−20 s**, after the failure | "
      + (f"**+{best[1]['lead_days']} days**, before it" if best else "see above") + " |")
    A("| AUC needed at the budget | 0.9992 | not the binding constraint here |")
    A("")
    if best:
        how, o = best
        A(f"**On T11, warning when the drift measure falls below "
          f"{o['warn_fraction']:.2f} fires {o['lead_days']} days before the "
          f"failure, with no healthy session warned first.** Same participant, "
          f"same recordings that gave −20 seconds within a session. What "
          f"changed is how often the monitor is asked to decide.\n")
        A("Two things that sentence does **not** say. It is one degradation "
          "event in one participant, so it describes what happened rather than "
          "what would happen again. And the association behind it does not "
          "survive both robustness checks on either participant — see the "
          "section below, which is the more important one.\n")
    A("The tables also show the tradeoff has not vanished, it has moved somewhere "
      "affordable: a looser threshold buys more lead time and costs recalibrations "
      "nobody needed. That pair is reportable, which is the whole point — within "
      "a session it was not, because no threshold bought useful lead at any cost.\n")

    A("## The robustness checks disagree, and that is the finding\n")
    rr = {k: v["robustness"] for k, v in result["participants"].items()}
    if "T11" in rr and "T5" in rr:
        A("| | T11 | T5 |")
        A("|---|---|---|")
        A(f"| Raw rho | {rr['T11']['raw_rho']:+.3f} | {rr['T5']['raw_rho']:+.3f} |")
        A(f"| Partial, day controlled | {rr['T11']['partial_rho']:+.3f} "
          f"(p = {rr['T11']['partial_p']:.3f}) | {rr['T5']['partial_rho']:+.3f} "
          f"(p = {rr['T5']['partial_p']:.3f}) |")
        A(f"| First differences | {rr['T11']['diff_rho']:+.3f} "
          f"(p = {rr['T11']['diff_p']:.3f}) | {rr['T5']['diff_rho']:+.3f} "
          f"(p = {rr['T5']['diff_p']:.3f}) |")
        A(f"| Sessions | {result['participants']['T11']['n_sessions']} | "
          f"{result['participants']['T5']['n_sessions']} |")
        A("")
        A("**Neither participant passes both checks.** T11 survives first "
          "differences and falls just short on the partial; T5 is the other way "
          "round, and on differences its correlation does not merely vanish, it "
          "changes sign. At 15 sessions and 6, that is what a genuinely "
          "unsettled result looks like.\n")
    A("So the honest statement is **not** \u201cthe drift measure predicts "
      "performance\u201d. It is: *on two participants, a drift measure and a "
      "performance measure both decline over months; they correlate strongly "
      "while that shared trend is left in, and the association is weaker and "
      "inconsistent once it is removed.* The lead times above are a true "
      "description of what happened in T11's record. They are not yet evidence "
      "that it would happen again.\n")

    A("## What would have to be true before this is a result\n")
    A("1. **Preregister it.** Thresholds, failure definition and predicted lead "
      "time written down before another dataset is touched.")
    A("2. **Settle whether the association survives controls**, on more than two "
      "participants. The partial and difference tests disagree here and neither "
      "sample can arbitrate.")
    A("3. **Get a false-alarm rate that means something.** One degradation event "
      "on T11 cannot estimate how often this fires when nothing is wrong. That "
      "needs more participants, or the rig, where onsets are constructed — which "
      "is what the rig was built for.")
    A("4. **Rule out the confounds.** `scripts/46_day_predictors.py` already "
      "exists to test whether a third factor moves both series.")
    A("5. **Check it is not the baseline ageing.** The measure is relative to "
      "the first session, so anything monotone will correlate with it. A local "
      "re-baselining arm is the control.")
    A("")
    A("**Only the first is free.** The rest is December work, and it is a better "
      "use of the rig than the comparison it was originally built for, because "
      "it tests something that might work rather than confirming something that "
      "does not.")

    (REPORTS / "SESSION_LEVEL_MONITOR.md").write_text("\n".join(L))
    print("\n".join(L[2:]).replace("**", ""))
    print(f"\nwrote {REPORTS / 'SESSION_LEVEL_MONITOR.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
