# -*- coding: utf-8 -*-
"""Front matter and Sections 1-4."""
from kit import *
from reportlab.platypus import PageBreak, Spacer, NextPageTemplate
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.lib.units import inch


def front_matter():
    s = []
    s += [Spacer(1, 1.05*inch)]
    s += [HRFlowable(width='38%', thickness=3, color=ACCENT, spaceAfter=16)]
    s += [Paragraph('Technical and Scientific Audit', S['title'])]
    s += [Paragraph('Detecting failure in chronic intracortical brain&#8211;computer '
                    'interface decoders', S['subtitle'])]
    s += [Spacer(1, 6)]
    s += [Paragraph('A complete, evidence-anchored review of the repository, its data, '
                    'its code, its statistics, its retracted claims and its readiness '
                    'for competition &#8212; together with a findings-driven design for '
                    'the original data-collection component.', S['note'])]
    s += [Spacer(1, 26)]
    s += TBL(None, [
        ['Repository', M('gnair40/bci-ews-research')],
        ['Branch audited', M('claude/isef-research-pipeline-9zt4uq')],
        ['HEAD commit at audit', M('07cb392767a101321e30c99f679ecb94e0ed70cf')],
        ['Commits in history', '123 (first 34dcb05, 16 Aug 2026; last 07cb392, 5 Sep 2026)'],
        ['Working tree', 'clean at time of audit'],
        ['Audit date', '6 September 2026'],
        ['Audit method', 'Direct inspection of the working tree, the full git history, '
                         'and re-execution of the project&#8217;s own verification gates'],
        ['Verification re-run', '93 / 93 headline claims reproduced from data files'],
    ], [0.24, 0.76], fs=8.6)
    s += [Spacer(1, 20)]
    s += CALLOUT(
        'This report was produced by inspecting primary evidence in the repository: '
        'files, git objects, commit messages, JSON manifests, checksums, and the output of '
        're-running the project&#8217;s scripts. Where a fact could not be recovered from '
        'that evidence, it is labelled '
        + B('UNRECOVERABLE') + ' rather than inferred. Nothing in this report is invented. '
        'Section&nbsp;0 states the audit&#8217;s own limits before any finding is presented.',
        tone='flag', label='Standard of evidence')
    s += [Spacer(1, 14)]
    s += [Paragraph('Contents follow. Sections 1&#8211;15 correspond to the audit scope '
                    'requested; Section&nbsp;0 records the audit&#8217;s method and limits; '
                    'Appendix&nbsp;A lists every verified claim.', S['note'])]

    # ---- table of contents
    s += [PageBreak()]
    s += [Paragraph('Contents', S['h1p'])]
    s += [HRFlowable(width='100%', thickness=0.5, color=RULE, spaceBefore=4, spaceAfter=12)]
    toc = TableOfContents()
    toc.levelStyles = [S['toc1'], S['toc2']]
    toc.dotsMinLevel = 0
    s += [toc]
    s += [NextPageTemplate('main')]
    return s


def section_0():
    s = H1('0. How this audit was carried out, and what it cannot see',
           'Section 0 · Method and limits')
    s += P(
        'Every statement in the sections that follow rests on one of four kinds of evidence, '
        'and the kind is named wherever the distinction matters.')
    s += TBL(['Evidence class', 'What it is', 'How it was obtained', 'Trust'], [
        ['Working-tree artefact',
         'A file present at HEAD &#8212; a script, a report, a JSON manifest, a checksum.',
         M('cat') + ', ' + M('ls') + ', direct read',
         'High &#8212; it is the thing itself'],
        ['Git-history artefact',
         'A commit message, a diff, a deletion, a rename, an author date.',
         M('git log') + ', ' + M('git show') + ', ' + M('git log --diff-filter'),
         'High, but records the author&#8217;s account of intent'],
        ['Recomputed result',
         'A number regenerated by running the project&#8217;s own code now.',
         M('python3 scripts/31_verify_claims.py') + ' and the four other gates',
         'High &#8212; reproduced during this audit'],
        ['Audit judgement',
         'An assessment of rigour, risk or readiness that no file states.',
         'Reasoning over the three classes above',
         'Marked as judgement in the text'],
    ], [0.17, 0.34, 0.28, 0.21], fs=8.0)

    s += H2('What was actually executed during this audit')
    s += P('The audit did not take the repository&#8217;s reports at their word. Five '
           'automated gates were re-run against the working tree, and all five pass:')
    s += TBL(['Gate', 'Script', 'Result on re-run'], [
        ['Claim verifier &#8212; recomputes every headline number from the data files',
         M('31_verify_claims.py'),
         B('93 / 93 match') + ' &#8212; &#8220;All 93 headline claims match the data files.&#8221;'],
        ['Reproducibility audit &#8212; imports, producers, ordering, references',
         M('55_reproducibility_audit.py'),
         B('PASS') + ' &#8212; 6 imports declared, 35 consumed files all produced, no ordering inversions'],
        ['Claims register &#8212; status of every claim, cross-checked against the verifier',
         M('56_claims_register.py'),
         B('38 entries') + ', 92 of 93 verifier checks cited by an entry'],
        ['Statistical hygiene linter &#8212; three known error classes over all scripts',
         M('61_statistical_hygiene.py'),
         B('PASS') + ' &#8212; 0 unreviewed sites, 8 deliberate sites documented'],
        ['Log coverage &#8212; every commit date accounted for in the research log',
         M('65_log_coverage.py'),
         B('PASS') + ' &#8212; 12 commit dates, 10 logged directly, 2 reconciled with a reason'],
    ], [0.38, 0.24, 0.38], fs=8.0)

    s += H2('Four things this audit cannot establish')
    s += P('Stated first, so that nothing later is read as stronger than it is.')
    s += UL([
        B('It cannot verify the raw data against Dryad today.') + ' The download manifest '
        'records a SHA-256 of ' + M('6d12b5db&#8230;') + ' for a 411,951,588-byte archive, and that '
        'digest matches what Dryad reported at download time on 25 August 2026. This audit '
        'confirms the manifest exists and is internally consistent; it did not re-download '
        '411&nbsp;MB to re-verify the hash against the live repository.',
        B('It cannot detect a script that runs and produces a wrong answer.') + ' The '
        'reproducibility gate is static analysis; the claim verifier checks that reported '
        'numbers match stored files, not that the computation behind those files is correct. '
        'The project&#8217;s own report says this in the same words, and it is the honest limit '
        'of self-checking.',
        B('It cannot recover reasoning that was never written down.') + ' Where a decision '
        'appears in a commit or a log entry, this report quotes it. Where it does not, the '
        'gap is marked ' + B('UNRECOVERABLE') + ' in Section&nbsp;3 rather than reconstructed.',
        B('It cannot assess the project against the 2026&#8211;27 ISEF forms,') + ' which had '
        'not been issued at the time the plan was drafted. Section&nbsp;12 assesses readiness '
        'against the structural requirements that are stable across form years and flags '
        'precisely which parts are form-year-specific.',
    ])
    s += H2('0.3 Register of unrecoverable information')
    s += P('Consolidated here so it is not scattered. Each item is something a reader might '
           'reasonably expect the repository to answer and which it does not.')
    s += TBL(['#', 'What cannot be recovered', 'Why', 'Does it affect a result?'], [
        ['U-1', B('The &#8220;literature review&#8221; the project repeatedly cites'),
         'Referenced and quoted in at least six files, and stated in the ISEF plan to be in the '
         'repository. No commit ever added it.',
         B('No result, but the framing.') + ' Its conclusions survive in the files that quote it; '
         'its reasoning does not. See 12.5.'],
        ['U-2', 'Which party proposed each scientific option',
         'The repository records what was decided and why, not who proposed it. Some log entries '
         'do name a researcher instruction; the attribution is not systematic.',
         'No. It affects the AI-disclosure narrative, not any number.'],
        ['U-3', 'The number of working sessions',
         '12 commit dates exist and 54 dated log headings, several sharing a date with markers '
         'like &#8220;(later)&#8221; and &#8220;(night)&#8221;. Session boundaries were never '
         'timestamped.',
         'No.'],
        ['U-4', 'What happened between 16 and 25 August 2026',
         'Eight days with no commits and no log entry spanning them.',
         'No.'],
        ['U-5', 'The exact conversation prompts',
         'Transcripts are not part of the repository artefact. Only outcomes are.',
         'No.'],
        ['U-6', 'The T11 arm of the combination study, as originally run',
         'Lost to a container restart. Recorded in commit ' + M('a713c83') + ' rather than hidden.',
         'No &#8212; it was re-run.'],
        ['U-7', 'Byte-level re-verification of the raw archive against Dryad ' + B('today'),
         'This audit did not re-download 411&nbsp;MB. The SHA-256 in the manifest matches what '
         'Dryad reported at download time.',
         'No, unless Dryad&#8217;s deposit has changed since v6.'],
    ], [0.05, 0.27, 0.38, 0.30], fs=7.9)

    s += CALLOUT(
        'One general finding shapes the whole audit and is stated here so that it is not '
        'mistaken for flattery later: ' + B('this project&#8217;s most valuable property is '
        'that it repeatedly caught itself being wrong, and left the wreckage in place.') +
        ' Five claims are formally withdrawn. Three published p-values were corrected from '
        'significant to null. Four separate checking tools were themselves buggy before they '
        'were useful, and each of those bugs is documented in the tool&#8217;s own report. '
        'That behaviour is rarer and harder than a positive result.',
        tone='good', label='Headline audit judgement')
    return s


def section_1():
    s = H1('1. Repository inspection', 'Section 1')
    s += P('The repository is a single-purpose research repository. There is no application '
           'code, no service, no deployment; every file exists to acquire data, analyse it, '
           'check the analysis, or record what happened.')

    s += H2('1.1 Physical inventory at HEAD')
    s += TBL(['Category', 'Count', 'Location', 'What it holds'], [
        ['Analysis scripts', '65', M('scripts/01&#8211;65_*.py'),
         '17,807 lines of Python, numbered in the order they were written'],
        ['Research documents', '28', M('research/'),
         'Preregistrations, frozen designs, the project definition, the ISEF plan, the log'],
        ['Reports', '45 Markdown + 3 HTML', M('reports/'),
         'One report per study, plus two rendered demonstrations and a plain-language guide'],
        ['Figures', '17 PNG', M('reports/figures/'),
         'Session timeline, performance over time, error distribution, missingness, decoder '
         'stability, EWS controls and power sweep, the MINDFUL reproduction, the two '
         '&#8220;why negative&#8221; panels, AUC by fault mode, calibration and staleness curves, '
         'decision rules. ' + B('Tracked in git only since commit ') + M('e421166') +
         '; previously gitignored, so every image link in every report was broken on GitHub'],
        ['Rendered write-ups', '3 HTML', M('reports/'),
         M('project_guide.html') + ' (plain-language guide), ' + M('monitor_demo.html') +
         ' (live demonstration, including the two cases it gets wrong), and '
         + M('bad_day_problem.html') + ', which is also published as a shareable artefact'],
        ['Processed data', '136 files', M('data/processed/'),
         'CSV and JSON intermediates; all tracked so the verifier runs on a fresh clone'],
        ['Raw data', '166 files, 825&nbsp;MB extracted', M('data/raw/'),
         'The Dryad archive, its extraction, and the download manifest &#8212; never modified'],
    ], [0.17, 0.11, 0.24, 0.48], fs=8.2)

    s += H2('1.2 Branches, tags, and what that implies')
    s += TBL(['Property', 'State', 'Audit note'], [
        ['Branches', M('claude/isef-research-pipeline-9zt4uq') + ' (working), ' + M('main'),
         'All 123 commits are on the working branch. No feature branches, no merges.'],
        ['Tags', B('None'),
         B('Finding.') + ' Nothing is tagged &#8212; not the design freeze, not the Phase&nbsp;1&#8211;2 '
         'closeout, not the Phase&nbsp;3 completion. The freeze is recoverable only because ' +
         M('FROZEN_DESIGN.json') + ' stores the commit hash inside itself. A tag would make '
         'the same fact visible from ' + M('git tag') + '. See Section&nbsp;14, roadmap item&nbsp;R7.'],
        ['Deleted files', '1', M('reports/BENCHMARK_T5_T5_local_trailing.md') + ' removed in '
         'commit ' + M('4dee00d') + '. A duplicated-prefix filename from a parameterisation bug, '
         'not a discarded result.'],
        ['Renames', '3', 'All documentation reorganisation; no analysis output was renamed.'],
        ['Working tree at audit', 'Clean', 'No uncommitted changes, no untracked analysis output.'],
        [B('Missing artefact'), B('1'),
         B('Finding.') + ' A &#8220;literature review&#8221; is cited as an existing document in '
         'at least six files and is stated in the ISEF plan to be &#8220;in the project '
         'repository&#8221;. It is not, and no commit ever added it. See Section&nbsp;12.3.'],
    ], [0.16, 0.17, 0.67], fs=8.2)

    s += H2('1.3 Churn: which files were rewritten most')
    s += P('Churn is a fingerprint of where the thinking happened. The three most-touched '
           'files are exactly the three that ought to be, if the project is what it claims '
           'to be.')
    s += TBL(['File', 'Commits touching it', 'Reading'], [
        [M('research/research_log.md'), '58',
         'Nearly one in two commits updates the log. The log is not a retrofit.'],
        [M('README.md'), '25',
         'Rewritten repeatedly as the question changed &#8212; including commit ' + M('6c27b21') +
         ', &#8220;Rewrite the README, which still described the abandoned question.&#8221;'],
        [M('scripts/31_verify_claims.py'), '19',
         'The verifier grew from a handful of checks to 93, one study at a time. '
         'Each addition is a commit that also added the study it checks.'],
    ], [0.30, 0.15, 0.55], fs=8.2)

    s += H2('1.4 Structural finding: raw and processed data are genuinely separated')
    s += P('The user&#8217;s standing constraint was that raw downloaded data must stay '
           'separate from processed data and must never be modified. This audit confirms the '
           'separation is real and enforced by structure, not merely by intention:')
    s += UL([
        M('data/raw/') + ' contains the Dryad ZIP, its extracted tree, the upstream README, '
        'and ' + M('download_manifest.json') + '. Nothing in the pipeline writes there after ' +
        M('01_download_dataset.py') + '.',
        M('data/processed/') + ' contains every derived artefact. The reproducibility gate '
        'independently confirms that all 35 consumed processed files have a producing script.',
        'The fault injector never writes a modified copy of the raw arrays. It writes an '
        + B('injection plan') + ' &#8212; episode identifiers, onsets, seeds &#8212; and applies '
        'the transformation in memory at scoring time. This is why 1,850 fault episodes cost '
        'kilobytes rather than gigabytes, and why the raw files are provably untouched.',
    ])
    s += CALLOUT(
        'The one structural weakness found in Section&nbsp;1 is the absence of tags. It costs '
        'nothing scientifically today, but it is the difference between &#8220;the design was '
        'frozen at ' + M('20db485') + ', and here is the file that says so&#8221; and '
        '&#8220;' + M('git show design-freeze') + '&#8221;. For a judge, the second is one command.',
        tone='flag', label='Section 1 finding')
    return s


def section_2():
    s = H1('2. Complete project timeline', 'Section 2')
    s += P('Reconstructed from commit author-dates, the dated headings in '
           + M('research/research_log.md') + ', and the timestamps embedded in the frozen '
           'design and injection plans. Every date below is from a git object or a file, '
           'not from memory.')

    s += H2('2.1 Commits per day, across the whole project')
    s += TBL(['Date', 'Commits', 'What happened that day'], [
        ['16 Aug 2026', '6', 'Repository created. README, research plan, learning roadmap, '
         'initial log. No data yet.'],
        ['&#8212; 17&#8211;24 Aug &#8212;', '0',
         B('Eight days with no commits.') + ' No commits. Cause is ' + B('UNRECOVERABLE') +
         ' from the repository; no log entry spans it.'],
        ['25 Aug 2026', '18', 'The single heaviest day. Network policy fixed, Dryad download '
         'script written against the real API, dataset downloaded and SHA-256 verified, '
         'loader built, exploration run, fixed-decoder claim tested twice, EWS controls and '
         'power sweep, MINDFUL baseline reproduced at r&nbsp;=&nbsp;0.985, deterioration '
         'definitions compared, freeze mechanism built.'],
        ['26 Aug 2026', '11', B('The hinge day.') + ' Design frozen (' + M('20db485') +
         ', 01:31&nbsp;UTC), observable selected, two amendments recorded, preregistered '
         'analysis run &#8212; negative, drift characterised, Phases 1&#8211;2 closed, project '
         'redefined backward from its final product, Amendment&nbsp;1 (no human participants) '
         'recorded, fault injector built.'],
        ['27 Aug 2026', '1', 'Reference decoder frozen; corpus severities recalibrated against '
         'it. Four bugs found that the corpus would otherwise have hidden.'],
        ['28 Aug 2026', '24', B('The largest day.') + ' Grading system built before the monitor; '
         'decoder-guard written; first benchmark (every detector fails the silence gate); '
         'local re-baselining; causal detrending; T5 transfer; full 36- then 48-configuration '
         'benchmark; task-change test; achievability; threshold-bound correction; the v2 '
         'prediction recorded and falsified; decision-rule comparison; the aggregation limit.'],
        ['30 Aug 2026', '1', 'One-measurement-per-session finding lands. Logged under the '
         '28 August heading &#8212; the session crossed midnight.'],
        ['31 Aug 2026', '4', 'Phase 3 consolidated into one report; the &#8220;participant&#8221; '
         'terminology note; feature study preregistered; live demonstration built.'],
        ['1 Sep 2026', '9', 'README rewritten; documents verified against data; feature study '
         'frozen, implemented, run &#8212; null; an overclaim fixed that rendering the demo exposed.'],
        ['2 Sep 2026', '11', 'Combination study (null); calibration efficiency (the first '
         'non-null positive); staleness; day variance with the fault-mix bug fixed; the first '
         'preregistered positive, P5.'],
        ['3 Sep 2026', '11', 'Abstention (null); day effect across detectors; the ceiling '
         'challenge that forced a retraction; unambiguous episodes; per-day chance; severity '
         'ladder; window overlap; reproducibility audit; claims register; attribution accuracy.'],
        ['4 Sep 2026', '15', 'Mode separability; per-mode detection; the pooled-window sweep '
         'that unpublished three results; the hygiene linter; figures and processed files '
         'un-gitignored.'],
        ['5 Sep 2026', '12', 'Invariant detector (worse); invariant attribution (worse); '
         'original data-collection design recorded; log coverage gate; published write-up '
         'brought current.'],
    ], [0.13, 0.08, 0.79], fs=8.0)

    s += H2('2.2 The five phases, and what closed each one')
    s += TBL(['Phase', 'Dates', 'Question it asked', 'How it closed'], [
        ['0 &#8212; Scoping', '16 Aug',
         'What is this project going to be?',
         'A plan and a roadmap. Superseded on 26 Aug.'],
        ['1 &#8212; Foundation', '25 Aug',
         'Is the data real, is it usable, does my pipeline work?',
         'Dataset verified by checksum; published result reproduced at r&nbsp;=&nbsp;0.985; '
         'detector validated on synthetic systems with known answers.'],
        ['2 &#8212; The preregistered test', '25&#8211;26 Aug',
         'Do early-warning signals precede decoder decline?',
         B('Negative, and overturned by its own prespecified limitation check.') +
         ' The indicator rose faster during health (&#964;&nbsp;=&nbsp;+0.857) than overall '
         '(&#964;&nbsp;=&nbsp;+0.743).'],
        ['3 &#8212; Build the ground truth', '26 Aug &#8211; 1 Sep',
         'If observational data cannot answer this, what can?',
         '1,850 fault episodes with onsets locked under checksum; a grading system built '
         'before the monitor; 48 configurations benchmarked; ' + B('0 pass all five gates') + '.'],
        ['4 &#8212; Interrogate the negative', '2&#8211;5 Sep',
         'Why did it fail, and is the failure real or an artefact of my own method?',
         'Twelve further studies, each preregistered. Five claims withdrawn, three p-values '
         'corrected, four checking tools debugged. The cause is located at '
         'lag-1&nbsp;r&nbsp;=&nbsp;0.995.'],
    ], [0.16, 0.12, 0.30, 0.42], fs=8.0)

    s += H2('2.3 Frozen artefacts, with their timestamps')
    s += P('These are the objects that make the preregistration claim checkable. Each carries '
           'its own creation time and the commit it was created at.')
    s += TBL(['Artefact', 'Frozen at (UTC)', 'At commit', 'What it locks'], [
        [M('research/FROZEN_DESIGN.json'), '2026-08-26 01:31:10', M('20db485'),
         'Phase 1&#8211;2 analysis: participant, variable, level, method, boundary day 758, '
         'p&nbsp;=&nbsp;0.0018, plus SHA-256 of ' + M('blocks.csv') + ' and ' + M('trials.csv') +
         '. Two amendments, both dated before the analysis.'],
        [M('data/processed/injection_plan.json'), '2026-08-27 17:48:12', M('6edf505'),
         'T11: 1,073 episodes, master seed 20260826, onsets in the 0.25&#8211;0.55 window of '
         'each block, per-episode seeds. ' + M('episodes_sha256') + ' = ' + M('37faf7dc&#8230;') +
         '. One amendment, with its reason recorded.'],
        [M('data/processed/injection_plan_T5.json'), '2026-08-28 02:14:02', M('f2d6efc'),
         'T5: 777 episodes, same seed and design. ' + M('episodes_sha256') + ' = ' +
         M('3c96508c&#8230;') + '. No amendments.'],
        [M('research/FEATURE_STUDY_FROZEN.json'), '1 Sep 2026', M('0950c04'),
         'Four feature families named and the list closed; success criterion fixed at '
         '+0.05 AUC on ' + B('both') + ' participants in the same direction.'],
        [M('research/COMBINATION_STUDY_FROZEN.json'), '2 Sep 2026', M('32aa623'),
         'How the four-component decomposition generalises to new feature families.'],
        [M('research/DETECTOR_V2_RECORD.json'), '28 Aug 2026', M('4cf5f57'),
         'A prediction about detector v2, committed while the results files were untouched. '
         'Outcome: satisfied on T11, falsified on T5, ' + B('not adopted') + '.'],
    ], [0.26, 0.13, 0.09, 0.52], fs=7.9)

    s += CALLOUT(
        'The ordering in 2.3 is the load-bearing fact of the whole project. '
        'The injection plan &#8212; which fixes ' + B('when every fault begins') + ' &#8212; was '
        'written on 27&#8211;28 August. The grading harness came after it (commit ' + M('e161594') +
        ', &#8220;Build the grading system before the monitor exists&#8221;), and '
        + M('decoder-guard') + ' itself came after that (' + M('bf5e8c0') + ', &#8220;Add '
        'decoder-guard, written before the baseline scores were read&#8221;). '
        'The ground truth could not have been tuned to the detector, because the detector did '
        'not exist. That ordering is visible in ' + M('git log') + ', not merely asserted.',
        tone='good', label='Why the timeline matters')
    return s


def section_3():
    s = H1('3. Claude Code activity audit', 'Section 3')
    s += P('This section audits what the AI assistant did in this repository, what it got '
           'wrong, and what cannot be recovered. It is included because ISEF treats undisclosed '
           'or misdescribed AI use as grounds for disqualification, and because an honest '
           'account of tool use is itself part of the paper trail.')

    s += H2('3.1 What is recoverable, and what is not')
    s += TBL(['Question', 'Answer', 'Source'], [
        ['Who authored the commits?',
         'All 123 commits are authored ' + M('Claude <noreply@anthropic.com>') + '. The commits '
         'were made by the assistant under the researcher&#8217;s direction, in the '
         'researcher&#8217;s repository.',
         M('git log --format=%an')],
        ['Were the scientific decisions the assistant&#8217;s or the researcher&#8217;s?',
         B('Mixed, and the split is partly UNRECOVERABLE.') + ' The repository records '
         '<i>what</i> was decided and <i>why</i>, in commit messages and the log. It does not '
         'record which party proposed each option. Several log entries do name a researcher '
         'instruction &#8212; for example Amendment&nbsp;1 opens &#8220;The researcher has '
         'established that human participants are not available&#8221; &#8212; but that '
         'attribution is not systematic.',
         'Log headings; ' + M('PROJECT_DEFINITION.md') + ' Amendment 1'],
        ['How many working sessions were there?',
         B('UNRECOVERABLE as a count.') + ' Twelve distinct commit dates exist. The log has 54 '
         'dated headings, some of which are marked &#8220;(later)&#8221;, &#8220;(evening)&#8221;, '
         '&#8220;(late)&#8221;, &#8220;(night)&#8221; on the same date &#8212; so sessions are '
         'more numerous than dates, but the boundaries are not logged as timestamps.',
         M('grep "^## " research/research_log.md')],
        ['Did any work happen that left no trace?',
         B('At least once, yes, and it is recorded.') + ' Commit ' + M('a713c83') + ' notes the '
         'T11 arm of the combination study &#8220;lost to a container restart&#8221;. The '
         'ephemeral execution environment can lose in-flight work; the repository is the only '
         'durable record.',
         'Commit ' + M('a713c83')],
        ['What reasoning shaped the original framing?',
         B('Partly UNRECOVERABLE.') + ' The project repeatedly cites a &#8220;literature '
         'review&#8221; as the source of its framing, its threat model and its comparator choice, '
         'and quotes it directly. That document is not in the repository and was never committed. '
         'Its <i>conclusions</i> survive in the files that quote it; its reasoning does not.',
         M('grep -rn "literature review"') + '; ' + M('git log --all --diff-filter=A')],
        ['What were the exact prompts?',
         B('UNRECOVERABLE.') + ' Conversation transcripts are not in the repository and are not '
         'part of the artefact. Only their outcomes are.',
         '&#8212;'],
    ], [0.20, 0.55, 0.25], fs=8.0)

    s += H2('3.2 The commit gaps, and how each is accounted for')
    s += P('Gaps in a research record invite the question &#8220;what happened there?&#8221;, so '
           'they are enumerated rather than smoothed over.')
    s += TBL(['Gap', 'Length', 'Status'], [
        ['17&#8211;24 Aug 2026', '8 days, no commits',
         B('UNRECOVERABLE.') + ' The log jumps from &#8220;Day 1&#8221; on 16 Aug straight to '
         'dataset acquisition on 25 Aug. No entry explains the interval.'],
        ['29 Aug 2026', '1 day, no commits',
         'Bracketed by heavy days on 28 and 30 Aug. Not separately explained; consistent with '
         'a rest day.'],
        ['30 Aug 2026', 'Commits, no matching log heading',
         B('Reconciled, not hidden.') + ' The 30 Aug commits belong to the session logged as '
         '&#8220;28 August 2026 &#8212; One measurement per session&#8221;. The session crossed '
         'midnight.'],
        ['31 Aug 2026', 'Commits, no matching log heading',
         B('Reconciled.') + ' Split across three headings: two dated 28 August and one dated '
         '1 September.'],
    ], [0.17, 0.20, 0.63], fs=8.2)
    s += CALLOUT(
        'The handling of the last two entries is worth naming as a rigour finding. The obvious '
        'fix &#8212; re-dating the log headings to match the commits &#8212; was ' + B('explicitly '
        'refused') + '. Instead, ' + M('scripts/65_log_coverage.py') + ' was written to compare '
        'commit dates against log headings and to carry a ' + M('RECONCILED') + ' table naming '
        'each mismatch and its reason. Re-dating would have made the record <i>look</i> tidier '
        'while destroying the evidence that sessions ran past midnight. The gate now fails if '
        'any future commit date is neither logged nor reconciled.',
        tone='good', label='A correction that was deliberately not made')

    s += H2('3.3 Errors the assistant made, and how each was caught')
    s += P('Fourteen distinct errors are recoverable from commits and reports. They are listed '
           'in full because the pattern &#8212; and specifically ' + B('how') + ' each was '
           'caught &#8212; is more informative than the count.')
    s += TBL(['#', 'Error', 'Consequence had it stood', 'How it was caught'], [
        ['1', 'Fault-mix control compared a float to a string (' + M('e.severity') + ' vs '
         + M('"high"') + '), so the test was always False.',
         'A control that measured nothing looked exactly like a control that passed. '
         'Fixing it ' + B('changed a conclusion') + ': T5 is confounded, &#961;&nbsp;=&nbsp;0.886.',
         'Noticed because every day reported precisely 0.00'],
        ['2', 'Inverse-variance weighting applied to a bounded statistic (AUC).',
         'A pooled AUC inflated from 0.675 to 0.836 by over-weighting extreme days; '
         '&#961;&nbsp;=&nbsp;&#8722;0.913 between |AUC&#8722;0.5| and its standard error.',
         'Noticed because the number was implausibly good'],
        ['3', M('prob_better_than_chance') + ' stored an inverted quantity: ' + M('mannwhitneyu') +
         ' returns U<sub>1</sub>, so U<sub>1</sub>/(nm) is P(error <i>exceeds</i> chance).',
         'A decoder 55&#176; better than chance was recorded as 0.273 and would have been read '
         'as its probability of beating chance.',
         'Found while checking an already-published recommendation'],
        ['4', 'Every p-value in ' + M('ACHIEVABILITY.md') + ' pooled windows within sessions.',
         'Sample size inflated ' + B('26.6&#215;') + '; four statistics published as exactly '
         '&#8220;p&nbsp;=&nbsp;0&#8221;; ' + B('three results significant as published are not '
         'significant') + ', including one at p&nbsp;=&nbsp;3.4e-15 that is actually 0.144.',
         'Noticed while decomposing a headline'],
        ['5', 'The reproducibility audit had three bugs of its own: f-strings parsed by regex '
         '(filename ' + M('}.csv') + '), filenames held in variables, and the audit listed as '
         'its own producer.',
         'Its first run reported 27 problems, of which ' + B('1') + ' was real. A tool that '
         'reports its own artefacts converts &#8220;unchecked&#8221; into &#8220;checked and '
         'clean&#8221;.',
         'Manual inspection of its own findings'],
        ['6', 'The statistical hygiene linter missed its own motivating example, because '
         + M('26_achievability.py') + ' wraps ' + M('mannwhitneyu') + ' in a local helper.',
         'The check would have certified the exact file it was written to catch.',
         'Asking &#8220;does it find the thing I already know is there?&#8221;'],
        ['7', 'A headline figure &#8212; the 11-of-13 sign test, p&nbsp;=&nbsp;0.011 &#8212; was '
         'computed in an ad-hoc shell one-liner while the verifier checked its JSON.',
         'A fresh clone would have failed that claim. ' + B('A verified claim resting on an '
         'unreproducible file looks exactly like a verified claim.'),
         'The reproducibility audit, first run'],
        ['8', 'An edit to ' + M('57_attribution_accuracy.py') + ' consumed its JSON write.',
         'Two claims would have had no backing file.',
         'The claim verifier, with two KeyErrors'],
        ['9', 'Dead line in ' + M('64_invariant_attribution.py') + ' (' +
         M('conf[(m, MAPPING and m)]') + ', immediately overwritten).',
         'None &#8212; numbers confirmed unchanged after removal. Recorded anyway.',
         'Code review before commit'],
        ['10', 'Overclaim: &#8220;decoder error is measurable online, without labels.&#8221;',
         'False &#8212; it needs the intended direction, which a deployed monitor does not have. '
         'The correction is ' + B('appended inline') + ' to the report, not edited away.',
         'Rendering the demo exposed it'],
        ['11', 'The WARN threshold search stopped at 59 while scores reach 3,200.',
         'Fifteen of 36 configurations were reported as &#8220;no operating point exists&#8221; '
         'when none existed <i>below an arbitrary bound</i> &#8212; a property of the search '
         'presented as a property of the detectors. Corrected to 1 of 48.',
         'Checking the search range against observed scores'],
        ['12', 'Wrong decoder API assumed (' + M('load_decoder') + ', ' + M('block_error') +
         ' do not exist).',
         'A script that could not run.',
         'Immediate execution failure'],
        ['13', 'Gates run <i>after</i> committing left ' + M('data/processed/*.json') + ' dirty.',
         'The repository would carry outputs that disagreed with the committed code.',
         'A stop hook. Order corrected to run gates, then commit.'],
        ['14', 'Figures and processed outputs were gitignored: 17 figures and 126 data files.',
         'Broken image links on GitHub, and a claim verifier that ' + B('could not run on a '
         'fresh clone') + '.',
         'Checked by actually cloning the repository'],
    ], [0.045, 0.275, 0.35, 0.33], fs=7.6)

    s += H2('3.4 What the error pattern shows')
    s += UL([
        B('Four of fourteen errors were in the checking tools themselves') + ' (#5, #6, #7, #8). '
        'The project names this explicitly &#8212; &#8220;the fourth time in this project that a '
        'checking tool was itself wrong before it was useful.&#8221; The lesson encoded in '
        'response is a good one: every new gate was tested against a defect already known to '
        'exist.',
        B('Three errors changed a published conclusion') + ' (#1, #4, #11). None was quietly '
        'patched. Each correction is a separate commit whose message names the invalidated '
        'claim, and each affected report carries the correction ' + B('inline') + ' rather than '
        'having the old text replaced.',
        B('The most dangerous class is the one that looks like success') + ' &#8212; #1 and #5 '
        'both produced output that resembled a passing check. Both were caught by a human-style '
        'question about plausibility (&#8220;why is this exactly 0.00?&#8221;, &#8220;why is this '
        'implausibly good?&#8221;) rather than by any automated gate.',
        B('One class of error is not covered by any gate:') + ' a computation that runs, produces '
        'a number, and is simply the wrong computation. The hygiene linter finds shapes, not '
        'wrong answers, and its own report says so.',
    ])
    s += CALLOUT(
        'Audit judgement, stated as judgement: the AI-assistance question a judge will ask is '
        'not &#8220;did you use a tool?&#8221; but &#8220;do you understand what it produced well '
        'enough to have caught it being wrong?&#8221; This repository&#8217;s answer is fourteen '
        'documented instances of exactly that. The evidence is strong. What is ' + B('missing') +
        ' is a single, plainly-worded AI-use disclosure written for the form &#8212; the ISEF plan '
        'has a &#167;C-AI placeholder flagged for re-checking against the 2026&#8211;27 rules, but '
        'no final text. Section&nbsp;12 carries this as a readiness gap.',
        tone='flag', label='AI use and the disclosure requirement')
    return s


def section_4():
    s = H1('4. What the research actually is', 'Section 4')
    s += P('This section states the project in its own terms &#8212; question, engineering goal, '
           'hypotheses, variables &#8212; drawn from ' + M('research/PROJECT_DEFINITION.md') +
           ' and the frozen designs, not paraphrased from the reports.')

    s += H2('4.1 The problem the project exists to solve')
    s += P('People with paralysis use intracortical brain&#8211;computer interfaces to control '
           'a cursor by imagining movement. Electrode arrays record neural activity; a '
           + B('decoder') + ' converts that activity into cursor motion. Over months and years '
           'the recording drifts &#8212; electrodes degrade, tissue responds, the neural code '
           'itself shifts &#8212; and the decoder silently becomes wrong. The current remedy is '
           'recalibration: stop, run a supervised block, refit. It costs the user time and it is '
           'scheduled by guesswork rather than by evidence of need.')
    s += P('The obvious research move is to look for an early-warning signal that precedes '
           'decline. ' + B('That is what Phases 1&#8211;2 did, and it is where the project found '
           'its real problem.'))

    s += H2('4.2 The hinge: why observational data cannot answer the original question')
    s += CALLOUT(
        'Lead time&nbsp;=&nbsp;(time performance crossed threshold)&nbsp;&#8722;&nbsp;(time the '
        'monitor warned). In observational data the first term is ' + B('defined by the '
        'analyst') + ', so lead time is partly an artefact of that definition. And the '
        'false-alarm rate cannot be estimated at all, because there is no known-healthy period '
        'of controlled length with no impending event. '
        + B('You cannot validate an early-warning system without a system in which you control, '
        'and therefore know, when the warning should have fired.'),
        tone='neutral', label='The argument that reorganised the project')
    s += P('Two things follow, and both are unusual for a high-school project. First, the '
           'negative result of Phases 1&#8211;2 is not a setback to be worked around &#8212; it is '
           'a statement about what any observational study of this kind can establish. Second, '
           'building a corpus with ' + B('known onset') + ' stops being an optional '
           '&#8220;original data&#8221; add-on and becomes ' + B('logically necessary') + ': it is '
           'the only configuration in which the primary claim is checkable at all.')
    s += NOTE('This argument is recorded in ' + M('research/PROJECT_DEFINITION.md') + ' &#167;1, '
              'written on 26 August 2026 &#8212; after Phases 1&#8211;2 and before any ISEF section '
              'was drafted. The document states its own purpose as working <i>backward</i> from '
              'the final product &#8220;so that every later choice is derived rather than '
              'assumed.&#8221;')

    s += H2('4.3 Scientific question, engineering goal, and hypotheses &#8212; kept separate')
    s += P('These are three different things, and the project keeps them apart deliberately, '
           'so that an engineering goal cannot quietly become a hypothesis.')
    s += TBL(['', 'Statement'], [
        [B('Scientific question'),
         'When a neural control interface degrades, does the <i>statistical structure</i> of the '
         'input signal change measurably <i>before</i> closed-loop task performance changes '
         '&#8212; and if so, is that change distinguishable from the change caused by the user '
         'simply doing something different?'],
        [B('Engineering goal'),
         'Build a monitor that converts that statistical change into a warning state early '
         'enough to act on, at a false-alarm rate low enough to be worth having, and with an '
         'attribution specific enough to choose the right action.'],
        [B('H1 &#8212; lead time'),
         'For injected degradations of known onset, ' + M('decoder-guard') + ' reaches WARN '
         'before performance crosses its degradation threshold, with median lead time '
         '&gt;&nbsp;0, at &#8804;&nbsp;1 false alarm per 10 hours of matched healthy operation.'],
        [B('H2 &#8212; specificity'),
         'Attribution accuracy across the four injected failure modes exceeds chance, and '
         'genuine task changes are classified TASK-CHANGE rather than as failures.'],
        [B('H3 &#8212; transfer'),
         'The identical monitor, with no refitting of its structure, passes the five gates on '
         'the public dataset &#8212; in particular, it is <i>silent</i> during T11&#8217;s healthy '
         'baseline, which the Phase 1&#8211;2 indicator was not.'],
        [B('H4 &#8212; impact'),
         'A recalibration policy driven by WARN performs no worse than fixed-schedule '
         'recalibration while performing significantly fewer recalibrations.'],
        [B('Falsification, fixed in advance'),
         'H1 is false if median lead time &#8804;&nbsp;0, or if the false-alarm constraint cannot '
         'be met at any operating point. H3 is false if the monitor trends during healthy '
         'baseline. ' + B('Any of these being false is a reportable result.')],
    ], [0.19, 0.81], fs=8.3)

    s += H2('4.4 Variables')
    s += TBL(['Class', 'Variable', 'Levels or definition'], [
        [B('Independent'), 'Failure mode', '4 injected: RATE_LOSS, CHANNEL_DROPOUT, GAIN_DRIFT, '
         'GEOMETRY_ROTATION &#8212; plus NONE and TASK-CHANGE as controls'],
        ['', 'Degradation rate', 'fast (0.10 of block), medium (0.35), slow (0.80)'],
        ['', 'Severity at endpoint', 'benign / sub-threshold / threshold-crossing, per mode'],
        ['', 'Onset time', 'Randomised in the 0.25&#8211;0.55 fraction of each block, ' +
         B('drawn and logged before any detector existed')],
        [B('Dependent'), 'Detection AUC', 'Window-level and episode-level; both reported, and '
         'the distinction is enforced by the claims register'],
        ['', 'Median lead time', 'Seconds between WARN and the performance crossing. ' +
         B('Never reported without its false-alarm rate')],
        ['', 'False-alarm rate', 'Per hour of matched healthy operation'],
        ['', 'Silence-gate pass', 'Fraction of healthy episodes on which the risk signal trends'],
        ['', 'Attribution accuracy', 'Fraction of episodes whose dominant component names the '
         'true mode, against a measured chance level'],
        [B('Controlled'), 'Decoder', 'Ridge regression to intended direction, ' + B('frozen') +
         ' after fitting; adaptive normalisation deliberately disabled to isolate degradation '
         'from the compensator'],
        ['', 'Windowing', '30&nbsp;s windows (1,500 bins at 20&nbsp;ms), stepped 5&nbsp;s '
         '(250 bins), identical across every configuration'],
        ['', 'Detector information', 'A detector sees ' + B('only') + ' the feature stream '
         '&#8212; never decoder output, task, performance, or fault label &#8212; and is fitted '
         'on healthy windows alone'],
        ['', 'Splits', 'By block. One free parameter chosen on validation. ' +
         B('Test set read once')],
        [B('Constant'), 'Source data', 'MINDFUL deposit, Dryad version 6, never modified'],
        ['', 'Random seed', 'Master seed 20260826; a derived per-episode seed stored with each '
         'episode'],
        ['', 'Chance level', 'Measured by shuffled pairing per participant and per day, ' +
         B('not assumed to be 90&#176;')],
    ], [0.13, 0.20, 0.67], fs=8.0)

    s += H2('4.5 The five gates, and why silence comes first')
    s += P('The validation standard is the project&#8217;s methodological product. It exists '
           'because Phase 1&#8211;2&#8217;s failure was not a low p-value &#8212; it was a '
           'significant result that meant nothing.')
    s += TBL(['#', 'Gate', 'Requirement', 'Why it exists'], [
        ['1', B('Silence'), 'No significant trend during healthy operation',
         B('Checked first.') + ' Phase 1&#8211;2&#8217;s indicator rose faster during health '
         '(&#964;&nbsp;=&nbsp;+0.857) than overall (+0.743). A detector that is never quiet '
         'cannot warn.'],
        ['2', B('Rate invariance'), 'Not explained by mean firing rate',
         'The Phase 1&#8211;2 indicator was 71% mean firing rate (R&#178;&nbsp;=&nbsp;0.707).'],
        ['3', B('Comparator'), 'Beat counting activity, not only the published baseline',
         'Mean firing rate alone predicted performance as well as the whole pipeline '
         '(&#961;&nbsp;=&nbsp;&#8722;0.880 against +0.858).'],
        ['4', B('Elapsed time'), 'Survive controlling for time',
         'Controlling for elapsed time, essentially nothing of the Phase 1&#8211;2 result '
         'remained.'],
        ['5', B('Detrend'), 'De-trend the series before testing it for a trend',
         'The frozen design omitted this. It is why recording drift produced p&nbsp;=&nbsp;0.0002. ' +
         B('It was not corrected retrospectively') + ' &#8212; doing so after seeing the outcome '
         'would have destroyed the preregistration.'],
    ], [0.03, 0.14, 0.31, 0.52], fs=8.0)
    return s
